### ISSUE TITLE
It is possible to close a task accidentally

### ISSUE THREAD

**Issue by miron4dev** [motivepick/motive-mobile-app#26]
Probably add additional menu using left swipe like in Mail app.

<img src="https://monosnap.com/image/u86PWLxrjbtRDNk87HFBeFsyZkiR4T.png" width="200px" >

**Comment by jshaipuka** [comment]
- [ ] Remove drag and drop list
- [ ] Add swipable list
- [ ] Swipable list actions: Complete, Edit, Delete (check if delete is supported on back-end)
- [ ] Remediate accidental completion: introduce button to list that will show all completed tasks. (User will be able to make task active again)
